spring:
  kafka:
    consumer:
      group-id: ms_mail_consumer
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  mail:
    host: 127.0.0.1
    port: 2525
    username: YOUR_GMAIL_USERNAME
    password: YOUR_GMAIL_PASSWORD
    properties.mail.smtp:
      auth: false
      starttls.enable: false
security:
  basic:
    enabled: false
